plugin: drupal
subDirectory: docroot

steps:
  - plugin: Script
    name: Composer setup
    script:
     - "composer selfupdate"
     - "composer install"
     - "export PATH=$PATH:$SRC_DIR/vendor/bin"
      #command: "nvm install 4.4.1"
      #command: "nvm use 4.4.1"
      #command: "rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*"
  - plugin: Script
    name: Run tests
    script:
      - "git diff --exit-code"
      - "./bolt.sh -Dbehat.run-server=true -Dbehat.launch-phantom=true build:validate:test"
